[MEMBERS] - OT226-22 Create Members model, migration and controller file
alkemyTech/OT226-Server pull request #10
Opened 2022-06-17 19:36 UTC by afrivera

## [OT226-22 ](https://alkemy-labs.atlassian.net/browse/OT226-22)

## Description

### Fields:

- id: INTEGER NOT NULL AUTO_INCREMENT
- name: VARCHAR NOT NULL
- facebookUrl: VARCHAR NULLABLE
- instagramUrl: VARCHAR NULLABLE
- linkedinUrl: VARCHAR NULLABLE
- image: VARCHAR NOT NULL
- description: VARCHAR NULLABLE
- timestamps y softDeletes

## Evidence Table
<img width="403" alt="desc table members" src="https://user-images.githubusercontent.com/82002776/174390461-a6a9404c-dc8a-4ff0-84f8-428ef41abf26.PNG">

## Evidence Code

<img width="919" alt="model y migration members" src="https://user-images.githubusercontent.com/82002776/174390524-4d45b7de-1a44-4434-89ff-cddc13959297.PNG">

2022-06-17 19:47 UTC, DAngello-Garcia requested changes
El campo name es not null y el nombre del modelo debe ser en singular

2022-06-17 20:12 UTC, Franckfer approved these changes

2022-06-17 22:14 UTC, gabodmc requested changes
modelos en singular, controladores en plural

2022-06-18 02:16 UTC, DAngello-Garcia approved these changes

2022-06-18 17:29 UTC, gabodmc approved these changes
Muy buen PR!

2022-06-18 19:48 UTC, merged