[News] - OT226  Create Model, Migration, and News Base Controller
alkemyTech/OT226-Server pull request #12
Opened 2022-06-18 15:11 UTC by raoole20

https://alkemy-labs.atlassian.net/browse/OT226-19

 ### Description 
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
content: TEXT NOT NULL
image: VARCHAR NOT NULL
categoryId: Clave foranea hacia ID de Categories
timestamps y softDeletes

### Evidence 
![image](https://user-images.githubusercontent.com/98604463/174444694-bd8d6a51-b1c8-4d81-8369-e2757fe621d1.png)

2022-06-18 15:47 UTC, DAngello-Garcia requested changes
Está bien, solo revisar los comentarios

2022-06-18 15:47 UTC, DAngello-Garcia commented on database/migrations/20220618150230-create-new.js
> +        type: Sequelize.INTEGER
Gabi mencionó que es buena práctica tener explícito lo de NOT NULL, entonces yo se lo añadiría

2022-06-18 15:47 UTC, DAngello-Garcia commented on database/models/new.js
> +      // define association here
Falta especificar la otra relación _models.Category.hasMany(New)_

2022-06-18 16:18 UTC, afrivera approved these changes
resolviendo los comentarios de @DAngello-Garcia diría que esta bien, para una proxima solo sube los cambios de los archivos que te pidieron, continúa así que vas muy bien

2022-06-18 17:37 UTC, gabodmc requested changes
Esta todo muy bien. Solo hay que excluir el package.json del pr

2022-06-18 17:37 UTC, gabodmc commented on package.json
> -    "sequelize": "^6.19.0",
No subir cambios del package.json

2022-06-18 17:39 UTC, nicoescudero commented
Al igual que los chicos, esta bien, solo debes hacer esos cambios en los archivos

2022-06-20 13:18 UTC, gabodmc approved these changes
Siguen los archivos modificados, pero no van a traer complicaciones. Buen pr!

2022-06-20 13:21 UTC, gabodmc requested changes

2022-06-20 13:21 UTC, gabodmc commented on database/models/new.js
> +      // define association here
Adhiero al comentario de D'angello

2022-06-20 16:07 UTC, gabodmc requested changes
Una minima correccion y estaria

2022-06-20 16:07 UTC, gabodmc commented on database/models/new.js
> +      });
Agregar esto para darle la asociación al modelo de Comment: 

   New.hasMany( models.Comment, {
        foreignKey: 'newId',
      })

2022-06-20 19:08 UTC, gabodmc approved these changes
Buenas correcciones en este PR!

2022-06-20 19:15 UTC, Raikul requested changes
Habría que remover el package-lock?

2022-06-20 19:19 UTC, gabodmc commented
> Habría que remover el package-lock?

Cuando haga el merge, que tome los cambios de dev y no los de el para que no los pise y ahi ya resuelve el problema

2022-06-20 19:33 UTC, Raikul approved these changes
Dale nomas

2022-06-20 20:57 UTC, DAngello-Garcia approved these changes

2022-06-20 21:04 UTC, merged