[FIX - ORGANIAZTION] Create model, migration and controller
alkemyTech/OT226-Server pull request #19
Opened 2022-06-20 22:57 UTC by AlexAc0226

id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
image: VARCHAR NOT NULL
address: VARCHAR NULLABLE
phone: INTEGER NULLABLE
email: VARCHAR NOT NULL
welcomeText: TEXT NOT NULL
aboutUsText: TEXT NULLABLE
timestamps y softDeletes

Evidence: 
![image](https://user-images.githubusercontent.com/88632261/174686697-20a44905-c447-4a34-a11c-eebd1e650181.png)

2022-06-20 23:34 UTC, gabodmc requested changes
Organization en singular

2022-06-21 01:23 UTC, AlexAc0226 commented
Evidence:
![image](https://user-images.githubusercontent.com/88632261/174696927-81154016-1ffc-4f21-bd36-cd62eb793b0f.png)

2022-06-21 01:31 UTC, dangello-g approved these changes

2022-06-21 02:01 UTC, Franckfer requested changes
creo que te esta generando conflictos este archivo con la migracion, ya que tiene el campo deletedAt, pero a este le falta el paranoid:true

2022-06-21 02:01 UTC, Franckfer commented on database/models/organization.js
>    });
creo que te esta generando conflictos este archivo con la migracion, ya que tiene el campo deletedAt, pero a este le falta el paranoid: true

2022-06-21 02:44 UTC, afrivera approved these changes
buen PR

2022-06-21 02:44 UTC, afrivera commented on database/models/organizations.js
> +'use strict';
los archivos siguen estando en plural, elimina ambos y crealos en singular

2022-06-21 14:11 UTC, gabodmc approved these changes

2022-06-21 15:37 UTC, Franckfer approved these changes

2022-06-21 18:38 UTC, merged