[FIX]- OT226-16
alkemyTech/OT226-Server pull request #20
Opened 2022-06-20 23:23 UTC by afrivera

## [FIX]- OT226-16

- rename role migration and model file

this fix does not affect the content of the member file.

2022-06-20 23:35 UTC, gabodmc approved these changes

2022-06-21 00:28 UTC, DAngello-Garcia requested changes
Solo quitar la relación en el modelo. De resto, todo bien

2022-06-21 00:28 UTC, DAngello-Garcia commented on database/models/role.js
> +      Role.belongsTo( models.User, {
Esta relación va definida en el modelo User, no aquí

2022-06-21 12:33 UTC, gabodmc approved these changes

2022-06-21 15:23 UTC, raoole20 approved these changes
se ve bien

2022-06-21 15:35 UTC, afrivera commented on database/models/role.js
> +      Role.belongsTo( models.User, {
Realizado

2022-06-21 15:43 UTC, DAngello-Garcia approved these changes

2022-06-21 15:45 UTC, merged