[controller - new ]  OT226-47 new controllers
alkemyTech/OT226-Server pull request #25
Opened 2022-06-21 15:53 UTC by raoole20

https://alkemy-labs.atlassian.net/browse/OT226-47

### Description
AS admin user
I WANT to add a novelty in the system
TO be able to inform the News of the NGO

Criteria of acceptance:
POST /news - must validate the existence of the submitted fields, to store the record in the news table. Before storing it, you will need to assign the type column to it with the value "news".

### Evidence
![image](https://user-images.githubusercontent.com/98604463/174841957-86b1b114-f090-49e5-b131-ad4a5d430073.png)

**Error msg**
![image](https://user-images.githubusercontent.com/98604463/174842305-914d9d32-7248-4813-bfc3-17c6dfd53783.png)

**code schema**
![image](https://user-images.githubusercontent.com/98604463/174842572-19fe8b73-ec7b-42c6-b37d-ce56dab0cde6.png)

2022-06-21 16:02 UTC, gabodmc requested changes
Algunas correcciones para realizar

2022-06-21 16:02 UTC, gabodmc commented on schemas/new.js
> +}
El schema es solo un schema y no una funcion. La responsabilidad de validar y devolver debe estar dentro del middleware

2022-06-21 16:02 UTC, gabodmc commented on database/migrations/20220618150230-create-new.js
> +      },
Archivo fuera del scope

2022-06-21 16:02 UTC, gabodmc commented on database/models/new.js
> +    type: DataTypes.STRING,
Archivo fuera del scope

2022-06-21 16:02 UTC, gabodmc commented on routes/news.js
> +router.post('/', createNew, post)
router.post('/', function(schema), post)

2022-06-21 16:02 UTC, gabodmc commented on routes/news.js
> +const { createNew } = require('../schemas/new')
a esto se lo deberia llamar como newsSchema

2022-06-21 23:55 UTC, Raikul approved these changes
Buen PR. La vanguardia de la validación.

2022-06-22 00:01 UTC, gabodmc approved these changes
Muy bien resuelto!

2022-06-22 00:01 UTC, gabodmc commented on helpers/handleValidator.js
> +    return res.status(403).send({ errors: err.array() })
Y si lo llevan un paso mas adelante y devuelven un error con el constructor?

2022-06-22 00:03 UTC, Franckfer approved these changes
Buen PR

2022-06-22 00:05 UTC, merged