[ENDPOINT] Category Detail
alkemyTech/OT226-Server pull request #27
Opened 2022-06-21 20:22 UTC by AlexAc0226

AS admin user
I WANT to get information from an individual category
To be able to manage it

Criteria of acceptance:
GET a /categories/:id . It will show all the fields of a category based on the id sent by parameter. In the event that it does not exist, it will return an error with a 404 status code.

Evidence route:
![image](https://user-images.githubusercontent.com/88632261/174890035-ffbd3d01-ea42-403f-929e-4bbd12337499.png)

service/categories:
![image](https://user-images.githubusercontent.com/88632261/174890271-0be02452-605e-4408-9ba9-7f28cf756ba4.png)

controllers/categories:
![image](https://user-images.githubusercontent.com/88632261/174890467-1f2629b6-a3e1-472b-87da-142d90564ce2.png)

2022-06-21 20:31 UTC, gabodmc requested changes
El pr esta bien encaminado. Lo que seria la evidencia deberia mostrar imagenes del postman listando la categoria en caso de que funcione, y los casos de error (no encontrada/sin parametros9

2022-06-21 20:31 UTC, gabodmc commented on services/categories.js
> +exports.getCategories = async ({ id }) => {
getCategoryById en el servicio.

2022-06-21 22:34 UTC, gabodmc reviewed
Bien resuelto. Recordar poner la evidencia del postman y no solo la respuesta "OK"

2022-06-22 00:05 UTC, Franckfer approved these changes

2022-06-22 00:38 UTC, afrivera approved these changes
Buen PR

2022-06-22 01:35 UTC, gabodmc approved these changes

2022-06-22 04:08 UTC, AlexAc0226 commented
Eviden: route result GET categories/:id
![image](https://user-images.githubusercontent.com/88632261/174940576-d41d73b9-0c00-44d9-a227-051a1ac1c9f1.png)

2022-06-22 04:08 UTC, merged