[Contact] OT226-55 Create migration and Contacts model
alkemyTech/OT226-Server pull request #33
Opened 2022-06-22 17:58 UTC by raoole20

### Description

AS admin user
I WANT to store the data sent when completing a Contact Form
TO keep track of them

Criteria of acceptance:
By completing the Contact Form, it will be stored in the database. Table name: contacts. It will contain the fields name, phone, email, message, deletedAt (used for soft delete)

**relevant information**

I included userId to be able to create the relationship between user and contact

### Evidence
![image](https://user-images.githubusercontent.com/98604463/175105066-63d46835-c7bb-42a2-b61c-a3a218d9dd2e.png)

2022-06-22 18:16 UTC, dangello-g approved these changes
Está bueno. Lo único que falta es crear la relación en el modelo User

2022-06-22 19:16 UTC, gabodmc requested changes
Bastante bien, solo unos cambios

2022-06-22 19:16 UTC, gabodmc commented on database/migrations/20220622161319-create-contact.js
> +      userId: {
Fuera del scope de la card. Agregar solo los campos requeridos

2022-06-22 19:16 UTC, gabodmc commented on database/models/contact.js
> +      Contact.belongsTo( models.User, {
Esta asociación no es necesaria

2022-06-22 22:21 UTC, raoole20 commented on database/migrations/20220622161319-create-contact.js
> +      userId: {
pero me queda la duda, de como va a funcionar esto si no esta asosociado con el modelo de users

2022-06-23 02:37 UTC, Raikul approved these changes
Los cambios necesarios y nada más, buen PR

2022-06-23 02:43 UTC, afrivera requested changes

2022-06-23 02:43 UTC, afrivera commented on database/models/contact.js
> +    messege: DataTypes.STRING,
el campo te quedó mal escrito y puede afectar a futuro (message)

2022-06-23 12:30 UTC, gabodmc approved these changes
Buenas correcciones. Aprobadisimo

2022-06-23 12:31 UTC, gabodmc commented on database/models/contact.js
> +    messege: DataTypes.STRING,
+1

2022-06-23 12:32 UTC, gabodmc requested changes
Solo modificar el typo mencionado

2022-06-23 13:42 UTC, afrivera approved these changes
Excelente, buen PR

2022-06-23 13:44 UTC, gabodmc approved these changes

2022-06-23 13:46 UTC, afrivera requested changes

2022-06-23 13:46 UTC, afrivera commented on database/models/contact.js
> +    message: DataTypes.STRING,
Revisando, veo que le falta el campo deletedAt, si es posible agregarlo para que cuando se realicen operaciones crud no se rompa

2022-06-23 13:49 UTC, Raikul approved these changes
Corregido el typo ya estamos

2022-06-23 13:49 UTC, Raikul commented on database/models/contact.js
> +    message: DataTypes.STRING,
El deleted at está en la migración igual

2022-06-23 13:51 UTC, afrivera commented on database/models/contact.js
> +    message: DataTypes.STRING,
lo que pasa es que sequelize usa el modelo para comunicarse, y si le falta ese campo en el modelo te tira un error de que no encontro el campo

2022-06-23 14:00 UTC, afrivera approved these changes
Buen PR

2022-06-23 14:02 UTC, merged