[MIDDLEWARE] OT226-27 validate admin
alkemyTech/OT226-Server pull request #46
Opened 2022-06-23 19:35 UTC by nicoescudero

[OT226-27](https://alkemy-labs.atlassian.net/browse/OT226-27)
### Description
COMO usuario administrador
QUIERO restringir el acceso a cierto contenido
PARA mantener los datos protegidos 

Criterios de aceptación:
Deberá verificar el campo roleId, y permitir continuar si el usuario tiene rol correspondiente a administrador
### Middleware Use
id correspondiente a la tabla roles
![roles_table](https://user-images.githubusercontent.com/44248035/175379235-12252609-540b-41b1-85d2-d6a5255f2e1d.png)

Tabla de Usuarios: el primer usuario tiene roleId:1(user) el segundo roleId:2(admin)
![userss](https://user-images.githubusercontent.com/44248035/175379704-25734b70-cb27-4376-b98a-81c35963b099.png)

En el ejemplo solo podran acceder a la ruta de /news los que tengan rol de administradores:
![routes](https://user-images.githubusercontent.com/44248035/175380185-900e39d0-78da-43e3-a7eb-13b75456f472.png)
### Evidence
Token del primer usuario roleId:1(usuario) -- Respuesta: status 401 unauthorized user - permissions denied
![unauthorized_user](https://user-images.githubusercontent.com/44248035/175380360-cf1e35de-2d99-4d87-9b10-f49e80a3ea0e.png)
Token del segundo usuario roleId:2(admin) -- Respuesta: status 200 OK
![user_admin](https://user-images.githubusercontent.com/44248035/175381391-4123c7fd-750e-4a4a-b93f-7c8fb806de35.png)
Token expirado o no ingresado -- Respuesta: status 401 unauthorized user - access denied
![token_no_provided](https://user-images.githubusercontent.com/44248035/175381702-7c8d0f2f-e223-47f9-9ab2-2b8a51c90f05.png)

2022-06-23 19:41 UTC, gabodmc requested changes
Renombrar al middleware como jwt.js

2022-06-23 19:48 UTC, Franckfer approved these changes
Buen PR!

2022-06-23 19:56 UTC, gabodmc requested changes
Vi el JWT y me confundi. Este middleware se tiene que llamar "isAdmin", pero la logica de jwt esta de mas aca. Solo chequea el roll de admin.
La logica de JWT se tiene que tocar desde un middleware llamado "jwt" que tenga los metodos que vayan a usar de dicho middleware. Ejemplo: decode
En este caso, coordinar con quien tiene la logica de JWT

2022-06-24 01:55 UTC, AlexAc0226 approved these changes

2022-06-24 13:42 UTC, raoole20 requested changes

2022-06-24 13:42 UTC, raoole20 commented on middlewares/jwt.js
> +    const token = req.headers.authorization.split(' ')[1]
yo envie el token por "api key", no por "bearer token", esto va a romper por que no son las misma formas de enviar el token, ni de recuperarlo en la respuesta

2022-06-24 14:05 UTC, nicoescudero commented on middlewares/jwt.js
> +    const token = req.headers.authorization.split(' ')[1]
ok, si igual esa linea la voy a borrar

2022-06-24 14:31 UTC, afrivera approved these changes
Buen PR

2022-06-24 19:20 UTC, gabodmc approved these changes
Bien resuelto!

2022-06-24 19:31 UTC, raoole20 approved these changes

2022-06-24 19:31 UTC, merged