[ENDPOINT] OT226-37 authenticated user data
alkemyTech/OT226-Server pull request #53
Opened 2022-06-25 21:30 UTC by raoole20

[OT226-37](https://alkemy-labs.atlassian.net/browse/OT226-37)
### Descrition

I WANT to get my data
TO have knowledge of the information that I store in the system

Criteria of acceptance:
/GET auth/me - They must return the data of the authenticated user, obtaining it from the token sent in the Authorization header

### Evidence 

**success msg**
![image](https://user-images.githubusercontent.com/98604463/175791057-9e597093-f67b-4510-9c10-38f499df45c3.png)

2022-06-25 22:28 UTC, Franckfer approved these changes
Excelente PR!

2022-06-26 16:04 UTC, gabodmc requested changes
Estan muy bien los cambios. Solo agrego una sugerencia

2022-06-26 16:04 UTC, gabodmc commented on controllers/users.js
> +  getInformation: catchAsync(async (req, res, next) => {
Este getInformation me hace un poco de ruido. Iria por algo un poco mas informativo tipo getUserByToken o algo asi.

2022-06-27 00:13 UTC, gabodmc approved these changes

2022-06-27 01:55 UTC, DAngello-Garcia approved these changes
Buen PR

2022-06-27 12:02 UTC, merged