[Activities] Create model, migration and activity controller
alkemyTech/OT226-Server pull request #6
Opened 2022-06-17 12:09 UTC by nicoescudero

[OT226-21](https://alkemy-labs.atlassian.net/browse/OT226-21)
### Description
### Activities Model Fields:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
content: TEXT NOT NULL
image: VARCHAR NOT NULL
timestamps y softDeletes

### Evidence
![db_activities](https://user-images.githubusercontent.com/44248035/174294255-6c12ab95-4f35-42e8-b0d4-0bbef7c45b14.png)

### Migration Code 
![migration_activities](https://user-images.githubusercontent.com/44248035/174294202-d869bd3f-5589-4752-bec1-524c9e262d0e.png)

### Model Code
![model_activities](https://user-images.githubusercontent.com/44248035/174294296-fd859878-fb62-4ba8-8437-343da6c31ef7.png)

2022-06-17 12:51 UTC, raoole20 commented
I see everything fine

2022-06-17 13:55 UTC, gabodmc requested changes
Muy buen PR. Solo corregir el controlador que esta con mayusculas

2022-06-17 15:21 UTC, dangello-g requested changes
Está bien

2022-06-17 15:50 UTC, afrivera approved these changes
pinta bien

2022-06-17 16:03 UTC, gabodmc approved these changes
Buen PR!

2022-06-17 16:33 UTC, Raikul commented
En general se pondría Activitie o Activity? Sabe cómo pluralizarl Activity el Sequelize?

2022-06-17 16:47 UTC, Franckfer approved these changes
looks great!

2022-06-17 22:12 UTC, gabodmc requested changes
Buena acotación arriba. Hay que cambiar el modelo a Activity

2022-06-18 17:34 UTC, gabodmc approved these changes
Bien las correcciones. Quedo un buen pr!

2022-06-18 17:52 UTC, DAngello-Garcia approved these changes

2022-06-18 22:13 UTC, merged