[ENDPOINT] OT226-45 DELETE /categories/:id
alkemyTech/OT226-Server pull request #61
Opened 2022-06-27 20:21 UTC by DAngello-Garcia

[OT226-45](https://alkemy-labs.atlassian.net/browse/OT226-45)
### DESCRIPTION
COMO usuario administrador
QUIERO eliminar una categoría existente
PARA mantener la información actualizada

Criterios de aceptación:
DELETE /categories/:id - Deberá validar que la categoría existe y eliminarla, caso contrario devolver un error
### EVIDENCE
![ok](https://user-images.githubusercontent.com/63479291/176028612-0b8d38b7-768f-408d-a8a3-e616effde195.png)
![404](https://user-images.githubusercontent.com/63479291/176028624-7fa1f3ec-ef78-4c08-bf46-c21ec139cd72.png)

2022-06-27 20:25 UTC, gabodmc requested changes
Esta bien, pero falta algo

2022-06-27 20:25 UTC, gabodmc commented on routes/categories.js
> +router.delete('/:id', destroy)
no hay validacion de administrador

2022-06-27 22:14 UTC, afrivera reviewed
sería bueno que antes del merge resolvieras los conflictos de los archivos, Buen PR

2022-06-28 20:20 UTC, Franckfer approved these changes
buen PR, solo queda arreglar los conflictos

2022-06-28 23:28 UTC, closed without merging