[update] OT226-67 Modify organizations public endpoint
alkemyTech/OT226-Server pull request #76
Opened 2022-07-01 17:36 UTC by raoole20

[OT226-67](https://alkemy-labs.atlassian.net/browse/OT226-67)

### Description

COMO usuario
QUIERO ver los links de las redes sociales al entrar a la página
PARA poder acceder a ellas.

Criterios de aceptación:

Al devolver los datos en el endpoint de datos públicos, agregar los campos de redes sociales en la respuesta

### Evidence 
![image](https://user-images.githubusercontent.com/98604463/176943855-079f6fd6-b469-4857-a3f9-1f9dee40db80.png)

2022-07-01 18:26 UTC, Franckfer approved these changes
bien

2022-07-01 18:58 UTC, nicoescudero approved these changes
lo veo bien, buen pr!

2022-07-01 20:49 UTC, gabodmc requested changes
Agregar las redes al modelo y no hardcodeada

2022-07-02 15:17 UTC, gabodmc requested changes
Las redes son atributos del objeto organization. No ponerla por separado

2022-07-03 23:40 UTC, gabodmc approved these changes

2022-07-04 18:59 UTC, merged