[ENDPOINT] OT226-62 Add Slides to public endpoint
alkemyTech/OT226-Server pull request #77
Opened 2022-07-01 17:59 UTC by Franckfer

CARD [OT226-62](https://alkemy-labs.atlassian.net/browse/OT226-62)

<hr>

## Description

* AS a user
* I WANT to see Slides when I log in to the page
* TO be more informed about them.

### Acceptance criteria:

* In the Organization's public data endpoint, the list of Slides sorted by the "order" field should be added. 

* The Slides will be those belonging to the Organization, based on the organization_id field that must correspond to the Organization that is being returned.

<hr>

## Evidence

**Slides**
![slidesIMG](https://user-images.githubusercontent.com/75815125/176946869-d62b6473-8ac4-4141-9d1c-def3eef5f30a.PNG)

2022-07-01 19:01 UTC, nicoescudero approved these changes
buen pr

2022-07-01 19:58 UTC, afrivera approved these changes
Buen PR

2022-07-01 20:59 UTC, DAngello-Garcia approved these changes
Bien

2022-07-01 21:02 UTC, gabodmc requested changes
Solo un comentario

2022-07-01 21:02 UTC, gabodmc commented on controllers/slides.js
> -  }),
Por que se elimino todo esto?

2022-07-02 15:08 UTC, gabodmc approved these changes

2022-07-02 20:03 UTC, merged