[ENDPOINT] OT226-65 GET /backoffice/contacts
alkemyTech/OT226-Server pull request #80
Opened 2022-07-01 20:56 UTC by DAngello-Garcia

[OT226-65](https://alkemy-labs.atlassian.net/browse/OT226-65)

### DESCRIPTION
COMO usuario administrador
QUIERO obtener el listado de contactos
PARA llevar un control de los contactos recibidos.

Criterios de aceptación:

    Al ingresar a la ruta /backoffice/contacts, mostrar un listado de los contactos enviados en el sitio, obteniéndose desde el endpoint. 

    Este listado se mostrará en una tabla

### Evidence

- No contacts
![no_contacts](https://user-images.githubusercontent.com/63479291/176966796-e674b30d-2071-455b-847e-25b1e00d9091.png)

- Get list of contacts
![200](https://user-images.githubusercontent.com/63479291/176966832-3715cbb5-72c2-489f-b56a-697320b71bba.png)

2022-07-01 23:06 UTC, afrivera reviewed
No sé si estoy mal, pero esta card parece más de front que backend @gabodmc ?

2022-07-02 15:14 UTC, gabodmc commented
> No sé si estoy mal, pero esta card parece más de front que backend @gabodmc ?

Justo acabo de escribirles por slack sobre esto. Es un error de la card. Todo lo que les toque con "/backoffice" tienen que omitir esa porcion de la ruta.

2022-07-02 15:16 UTC, gabodmc requested changes
D'angello, el pr esta bien cumplido, pero la card esta mal planteada. Tendrias que dejar ese get /contacts en un router de contacts y protegido solo para admin. 
Esta bien lo que hiciste, pero esta mal lo que te pide, por eso te solicito este cambio.
Tambien te modifique la card en jira

2022-07-03 23:39 UTC, gabodmc approved these changes
Perfecto. Muy buen PR!

2022-07-04 20:12 UTC, afrivera approved these changes
Buen PR

2022-07-04 20:53 UTC, raoole20 approved these changes

2022-07-04 21:10 UTC, merged