[endpoin] OT226-72 Endpint members get
alkemyTech/OT226-Server pull request #81
Opened 2022-07-02 17:31 UTC by raoole20

[OT226-72](https://alkemy-labs.atlassian.net/browse/OT226-73)

### Description

COMO administrador
QUIERO listar los Miembros
PARA obtener información certera de los Miembros al día.

Criterios de aceptación:
GET /members - Devolverá todos los Miembros

### Evidence 
![image](https://user-images.githubusercontent.com/98604463/177010538-eff7dc7d-fcc7-494f-b614-fee661192367.png)

2022-07-03 23:23 UTC, Franckfer requested changes

2022-07-03 23:23 UTC, Franckfer commented on routes/menbers.js
> +
solo renombrar el archivo menbers a members, ya que eso generaría un conflicto, lo demas lo veo bien

2022-07-03 23:42 UTC, gabodmc requested changes

2022-07-03 23:42 UTC, gabodmc commented on routes/menbers.js
> +
+1

2022-07-04 17:17 UTC, Franckfer approved these changes

2022-07-04 20:10 UTC, gabodmc approved these changes

2022-07-04 20:14 UTC, afrivera approved these changes
Bien!! Buen PR

2022-07-04 21:02 UTC, merged