[USERS] - OT226-17 Create Users model, migration and controller file
alkemyTech/OT226-Server pull request #9
Opened 2022-06-17 18:42 UTC by DAngello-Garcia

[OT226-17](https://alkemy-labs.atlassian.net/browse/OT226-17)

### Description
Campos:
id: INTEGER NOT NULL AUTO_INCREMENT
firstName: VARCHAR NOT NULL
lastName: VARCHAR NOT NULL
email: VARCHAR UNIQUE NOT NULL
password: VARCHAR NOT NULL
photo: VARCHAR NULLABLE
roleId: Clave foranea hacia ID de Role
timestamps y softDeletes

### Evidence
![migrate](https://user-images.githubusercontent.com/63479291/174359278-c5166606-9299-4bc0-8494-9c4254e6cb32.png)
![model](https://user-images.githubusercontent.com/63479291/174359295-501b2151-bd89-4b86-bf0c-c5e19540b9d5.png)
![workbench](https://user-images.githubusercontent.com/63479291/174359306-eeaeeef9-21d1-479d-b6c9-a0c355aeb12f.png)

2022-06-17 21:13 UTC, Raikul approved these changes
Prolijo PR!

2022-06-17 22:02 UTC, Franckfer approved these changes
Buen PR!

2022-06-17 23:00 UTC, gabodmc requested changes
Buen PR, solo unos cambios

2022-06-17 23:00 UTC, gabodmc commented on database/models/user.js
> +      models.Role.hasMany(User)
User.belongsTo(models.Role , {foreignKey: 'roleId'})

2022-06-17 23:00 UTC, gabodmc commented on database/models/user.js
> +      this.belongsTo(models.Role)
Esta linea no va

2022-06-18 16:08 UTC, afrivera commented on database/models/user.js
> +      models.Role.hasMany(User)
@gabodmc me queda la duda si debe ser User.hasOne.... ya que en el role lo deje Roles.belongsTo... Sería bueno tener el DER para mirar todas las relaciones de las tablas que estamos generando

2022-06-18 16:21 UTC, afrivera approved these changes
resolviendo la inquietud que se le plante a Gabi me parece bueno, está muy bien!

2022-06-18 17:32 UTC, gabodmc approved these changes
Bien hechas las correcciones. Quedo muy bien el PR!

2022-06-18 17:32 UTC, gabodmc commented on database/models/user.js
> +    modelName: 'User',
Timestamps

2022-06-18 17:51 UTC, merged