[Endpint] OT226-80 Created Endpoint to list Comments
alkemyTech/OT226-Server pull request #92
Opened 2022-07-06 22:56 UTC by raoole20

[OT226-80](https://alkemy-labs.atlassian.net/browse/OT226-80)

### Description 
AS admin user
I WANT to get a list of Comments
TO moderate the same.

### Criteria of acceptance:
GET /comments - Will return all Comments, ordered by creation date, only the body field

### Evidence

![image](https://user-images.githubusercontent.com/98604463/177656588-282e6c09-07db-401b-961f-eb6898a5474a.png)

2022-07-06 23:27 UTC, nicoescudero approved these changes
Buen pr!

2022-07-06 23:52 UTC, DAngello-Garcia approved these changes

2022-07-07 04:16 UTC, Franckfer requested changes

2022-07-07 04:16 UTC, Franckfer commented on routes/index.js
> +const commetsRouter = require('./comments')
esto puede generar un error, se debería llamar commentsRouter falta una n, solo eso

2022-07-07 18:48 UTC, raoole20 commented on routes/index.js
> +const commetsRouter = require('./comments')
listo cambiado

2022-07-07 19:11 UTC, Franckfer approved these changes

2022-07-07 19:27 UTC, gabodmc approved these changes

2022-07-12 15:20 UTC, merged