[PAGINATION] OT226-87 Members
alkemyTech/OT226-Server pull request #97
Opened 2022-07-08 13:21 UTC by nicoescudero

[OT226-87](https://alkemy-labs.atlassian.net/browse/OT226-87)
### Description
AS A USER
I WANT to visualize the results of paginated Members
TO increase the speed of response

Acceptance Criteria:
When the request is made to list, the results should be paginated by 10. In the response, the results and urls for the previous and next page (if applicable) should be displayed. The current page will be obtained from the query parameter ?page

### Evidence
Page = 1  -- Response Status 200OK
![page1](https://user-images.githubusercontent.com/44248035/177998654-063a8ebc-e9d3-4702-87cb-f6fe2b829372.jpg)
Page = 10 -- Response Status 200OK
![pag10](https://user-images.githubusercontent.com/44248035/177998764-3123939a-1ddb-44e3-985a-6c1874fa4396.jpg)
Page = 0 -- Response Status 500 Error (number must be greater than 0)
![pageError0](https://user-images.githubusercontent.com/44248035/177999049-55b31f3c-04ed-4a52-96c2-c14112697362.jpg)
Page = aaa -- Response Status 500 Error (page parameter must be numeric)
![pageErrorString](https://user-images.githubusercontent.com/44248035/177999343-5e4d700f-bf0f-423c-8ace-3fb2b185d9dc.jpg)
If we do not enter the page parameter. The response returns all members
![members](https://user-images.githubusercontent.com/44248035/177999550-40fbe522-b92f-4de0-ad4f-8a06afac6c26.jpg)

2022-07-08 16:18 UTC, Franckfer approved these changes
buen PR

2022-07-11 17:45 UTC, DAngello-Garcia reviewed
Está bien, pero le falta devolver las urls de las páginas anterior y siguiente

2022-07-11 18:00 UTC, gabodmc requested changes
En lineas generales esta bien. El tema es que ya tienen un PR que se subio de paginacion, y hay diferencias con lo que estan respondiendo en la misma.
Van a tener que coordinar como quieren responder a la paginacion para que les muestre los mismos datos en cualquiera de los endpoints.

2022-07-12 00:37 UTC, afrivera approved these changes
Tomar las sugerencias planteadas, de resto lo veo bien

2022-07-13 21:14 UTC, gabodmc approved these changes

2022-07-13 21:15 UTC, merged